### ISSUE TITLE
How can I enable glow in nvim with lua

### ISSUE THREAD

**Issue by BearyDevs** [artanikin/vim-synthwave84#12]
How can I enable glow in nvim with lua.

Thank for teaching me :)

**Comment by BioWare** [comment]
> How can I enable glow in nvim with lua.
> 
> Thank for teaching me :)

This colorsceme doesn't have glowing. You can look at /synthwave-x-fluoromachine or on LunarVim, i saw how Chris was making glowing live on stream. Look at his profile
