### ISSUE TITLE
Color Offset in Theme

### ISSUE THREAD

**Issue by dannyh79** [artanikin/vim-synthwave84#3]
First off, a BIG thank you in porting synthwave84 to VIm! God know how much I miss the theme.

The color gone odd when I set the theme to `synthwave84` (top), yet `gruvbox` (bottom) works just fine. Would be great if you could help look into it, as I am not quite sure where went wrong:

![image](https://user-images.githubusercontent.com/30727089/70853728-e917fd00-1eec-11ea-9b9f-903728f74e6d.png)

![image](https://user-images.githubusercontent.com/30727089/70853757-59268300-1eed-11ea-87cc-457c9d00dd39.png)

Please let me know if there is any config that I need to provide for the issue.

**Comment by dannyh79** [comment]
Oh and a BIG thank you in porting synthwave84 to VIm! God know how much I miss the theme.

Let me know if there is any config that I need to provide for the issue.

**Comment by jwhitley** [comment]
HI @dannyh79, I'm not the maintainer, but from your screencaps I can think of two things to explore:

1. Do you have 24-bit color enabled in all of: vim, your terminal app, and tmux (if you're using it)? You can quickly test your terminal and/or tmux setup [using this script from StackOverflow](https://unix.stackexchange.com/questions/404414/print-true-color-24-bit-test-pattern).
2. Is transparency enabled in your terminal? I've had to either remove the `Normal` background color in color schemes to make them work well with even slightly transparent terminals, or else turn off transparency. This doesn't look like what's happening for you, but it's worth checking.

For what it's worth, I just installed vim-synthwave84 and definitely get the correct background color with this scheme using iTerm2 (3.x), recent neovim, and with or without tmux. So there's probably something in your local setup that's causing problems. Good luck!

(last but not least, I'll also offer my huge thanks to @artanikin for porting this from the VSCode theme!)

**Comment by dannyh79** [comment]
Hi @jwhitley Much appreciated the detailed guide! Thought I had the right color going a couple weeks after I opened this issue, which I totally forgot about.

From what I could recall it should've been the problem with the setup of Tmux, testing with the exact script you posted from StackOverflow. :)

Closing the issue as it was not relevant to `vim-synthwave84`.
