### ISSUE TITLE
Arguments color

### ISSUE THREAD

**Issue by RizaHKhan** [artanikin/vim-synthwave84#4]
This isn't an 'issue' but the color of the arguments inside Javascript is grey. I was hoping we could change it to something a bit more prominent. 

![image](https://user-images.githubusercontent.com/51720003/85912868-ca7cb200-b7fd-11ea-99f6-3f5ae98dc034.png)

Is this possible?

Thank you,

**Comment by artanikin** [comment]
I added highlights for the arguments.
You may need to install one of the plugins for better syntax highlighting. Use one of these plugins:
1. https://github.com/pangloss/vim-javascript
1. https://github.com/sheerun/vim-polyglot

Or create a directory syntax in the .vim folder and copy one of the files there:
1. https://github.com/pangloss/vim-javascript/blob/master/syntax/javascript.vim
1. https://github.com/sheerun/vim-polyglot/blob/master/syntax/javascript.vim

#5
